### Installing NumPy
`conda install numpy`
or
`pip install numpy`

### How to import NumPy
`import numpy as np`

### What’s the difference between a Python list and a NumPy array?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

### Why use NumPy?
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.


In [3]:
import numpy as np

### How to create a basic array?

np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [8]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [12]:
arr = np.array([1,2,3,4], dtype = np.float32)
print(arr)

[1. 2. 3. 4.]


In [16]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
arr = np.zeros((2,3))
print(arr)
arr = np.ones((2,3))
print(arr)

# ndArray with random number
arr = np.random.rand(2,3)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.49708311 0.20264738 0.14856251]
 [0.65669588 0.34448032 0.18276768]]


In [25]:
# I matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# Evently spcaed ndarray
arr = np.arange(5)
print(arr)
arr = np.arange(start=2,stop=10,step=2)
print(arr)

[0 1 2 3 4]
[2 4 6 8]


In [36]:
# np.linspace Return evenly spaced numbers over a specified interval.
arr = np.linspace(start=1,stop=2, num=50)
print(arr)

[1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1.65306122 1.67346939 1.69387755 1.71428571
 1.73469388 1.75510204 1.7755102  1.79591837 1.81632653 1.83673469
 1.85714286 1.87755102 1.89795918 1.91836735 1.93877551 1.95918367
 1.97959184 2.        ]


## Printing Arrays
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

* the last axis is printed from left to right,

* the second-to-last is printed from top to bottom,

* the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [97]:
a = np.arange(6)                         # 1d array
print('Array 1: ', '\n',a)
b = np.arange(12).reshape(4,3)           # 2d array
print('Array 2: ', '\n',b)
c = np.arange(24).reshape(2,3,4)         # 3d array
print('Array 3: ', '\n',c)

Array 1:  
 [0 1 2 3 4 5]
Array 2:  
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Array 3:  
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## Copies and Views

In [99]:
# No copy at all
a = np.arange(6)   
b = a
b is a

True

In [110]:
#View or Shallow Copy
a = np.arange(6) 
print('a : ', a)
c = a.view()
print('c : ', c)
print(c is a)
print(c.base is a) # c is a view of the data owned by a
c = c.reshape((2, 3)) 
print('c : ', c)
print(a.shape) # a's shape doesn't change
c[0, 2] = 1234
print('c : ', c)
print('a : ', a)

a :  [0 1 2 3 4 5]
c :  [0 1 2 3 4 5]
False
True
c :  [[0 1 2]
 [3 4 5]]
(6,)
c :  [[   0    1 1234]
 [   3    4    5]]
a :  [   0    1 1234    3    4    5]


Slicing an array returns a view of it:



In [112]:
#Deep Copy
a = np.arange(6) 
print('a : ', a)
c = a.copy()
print('c : ', c)
print(c is a)
print(c.base is a)

a :  [0 1 2 3 4 5]
c :  [0 1 2 3 4 5]
False
False


## Shape and Reshaping of ndArrays

In [41]:
arr = np.random.rand(2,3,4)
print('Array: ', arr)
print('Dimensions: ', arr.ndim)
print('Shape: ', arr.shape)
print('Size: ', arr.size)

Array:  [[[0.93015623 0.45972254 0.23927131 0.6599513 ]
  [0.27647296 0.45986848 0.98210672 0.54242061]
  [0.09520916 0.37985374 0.74065964 0.30989922]]

 [[0.62255624 0.80891048 0.81849312 0.82103094]
  [0.30379527 0.44247961 0.5011124  0.30540235]
  [0.70982198 0.5107274  0.66204653 0.48552047]]]
Dimensions:  3
Shape:  (2, 3, 4)
Size:  24


In [45]:
# Reshaping a ndArray
a = np.array([3,6,9,12])
np.reshape(a,(2,2))
print(a)

# -1 will auto calcualte the axis
a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,-1)))
print('Three columns :','\n',np.reshape(a,(-1,3)))

[ 3  6  9 12]
Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns : 
 [[ 3  6  9]
 [12 18 24]]


In [47]:
# Flattening a ndArray
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]
Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]
Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


But an important difference between flatten() and ravel() is that the former returns a copy of the original array while the latter returns a reference to the original array. This means any changes made to the array returned from ravel() will also be reflected in the original array while this will not be the case with flatten().

In [49]:
# Transpose of a NumPy array
a = np.array([[1,2,3],
[4,5,6]])
b = np.transpose(a)
print('Original','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)


Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
Expand along columns: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


## Indexing and Slicing of NumPy array

In [59]:
# Slicing 1-D NumPy arrays
# index format = [start:end:step-size]
# slicing includes the start index but excludes the end index.
# default start is 0 and step-size is 1
a = np.array([1,2,3,4,5,6])
print(a[3])
print(a[1:5:2])

4
[2 4]


In [58]:
# Slicing 2-D NumPy arrays
a = np.random.rand(3,4)
print(a)
print(a[0,2])
print(a[1,3])
print(a[2,3])

[[0.77140925 0.12681755 0.34290527 0.21559769]
 [0.9308305  0.30705729 0.75882857 0.45628551]
 [0.49709546 0.42892444 0.25729888 0.89437388]]
0.3429052730243729
0.45628550695038494
0.894373880825089


In [64]:
a = np.random.rand(3,4)
print(a)
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1:2])
print('Arbitrary values :','\n',a[0:1,1:3])


[[0.49323184 0.76179554 0.83524665 0.32677016]
 [0.63696938 0.05766509 0.54672443 0.72668904]
 [0.95465852 0.87349783 0.15119453 0.22443561]]
First row values : 
 [[0.49323184 0.76179554 0.83524665 0.32677016]]
Alternate values from first row: 
 [[0.49323184 0.83524665]]
Second column values : 
 [[0.76179554]
 [0.05766509]
 [0.87349783]]
Arbitrary values : 
 [[0.76179554 0.83524665]]


In [71]:
a = np.array([
    [[1,2],[3,4],[5,6]],# first axis array
    [[7,8],[9,10],[11,12]],# second axis array
    [[13,14],[15,16],[17,18]] # third axis array
])
# 3-D array
print(a)
# value
print('First array, first row, first column value :','\n',a[0,0,0])
print('First array last column :','\n',a[0,:,1])
print('First two rows for second and third arrays :','\n',a[1:,0:2,0:2])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
First array, first row, first column value : 
 1
First array last column : 
 [14 16 18]
First two rows for second and third arrays : 
 [[[ 7  8]
  [ 9 10]]

 [[13 14]
  [15 16]]]


## Stacking and Concatenating NumPy arrays
#### Stacking ndarrays
You can create a new array by combining existing arrays. This you can do in two ways:

* Either combine the arrays vertically (i.e. along the rows) using the vstack() method, thereby increasing the number of rows in the resulting array
* Or combine the arrays in a horizontal fashion (i.e. along the columns) using the hstack(), thereby increasing the number of columns in the resultant array

In [73]:
a = np.arange(0,5)
b = np.arange(5,10)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))

Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8 9]
Vertical stacking : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stacking : 
 [0 1 2 3 4 5 6 7 8 9]


In [75]:
# Concatenating ndarrays
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Concatenate along rows :','\n',np.concatenate((a,b),axis=0))
print('Concatenate along columns :','\n',np.concatenate((a,b),axis=1))

Array 1 : 
 [[0 1 2 3 4]]
Array 2 : 
 [[5 6 7 8 9]]
Concatenate along rows : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Concatenate along columns : 
 [[0 1 2 3 4 5 6 7 8 9]]


In [77]:
# append values to ndarray
a = np.array([[1,2],
             [3,4]])
np.append(a,[[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Broadcasting in NumPy arrays – A class apart!
Broadcasting is one of the best features of ndarrays. It lets you perform arithmetics operations between ndarrays of different sizes or between an ndarray and a simple number!

Broadcasting essentially stretches the smaller ndarray so that it matches the shape of the larger ndarray:

In [83]:
a = np.arange(10,20,2)
b = np.array([[2],[2]])
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Adding two different size arrays :','\n',a+b)
print('Multiplying two different size arrays :','\n',a*b)
print('Multiplying an ndarray and a number :',a*2)


Array 1 : 
 [10 12 14 16 18]
Array 2 : 
 [[2]
 [2]]
Adding two different size arrays : 
 [[12 14 16 18 20]
 [12 14 16 18 20]]
Multiplying two different size arrays : 
 [[20 24 28 32 36]
 [20 24 28 32 36]]
Multiplying an ndarray and a number : [20 24 28 32 36]


## Maths with NumPy arrays

In [86]:
# Basic arithmetic operations on NumPy arrays
a = np.arange(1,6)

print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)


Subtract : [-4 -3 -2 -1  0]
Multiply : [ 5 10 15 20 25]
Divide : [0.2 0.4 0.6 0.8 1. ]
Power : [ 1  4  9 16 25]
Remainder : [1 2 3 4 0]


In [90]:
# Mean, Median and Standard deviation
a = np.random.rand(3,4,4)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

Mean : 0.4655243677946497
Standard deviation : 0.2934990850626667
Median : 0.4770965300389343


In [92]:
# Min-Max values and their indexes
a = np.array([[1,6],
[4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


In [93]:
# get index of min and max
a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))


Min : [0 1 0]
Max : [1 2]


## Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

List: all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where



## Linear Algebra


In [114]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
np.linalg.inv(a)
j = np.array([[0.0, -1.0], [1.0, 0.0]])
print(j @ j )       # matrix product
y = np.array([[5.], [7.]])
print(np.linalg.solve(a, y))

[[1. 2.]
 [3. 4.]]
[[-1.  0.]
 [ 0. -1.]]
[[-3.]
 [ 4.]]
